version: "3.8"
   
services:
  findata:
    container_name: findata_service
    build: .
    depends_on:
      mongodb:
        condition: service_started
    networks:
      - invest-system

  mongodb:
    image: mongo:4.4-bionic
    container_name: findata_mongodb
    environment:
      - 'MONGODB_USER=findata'
      - 'MONGODB_PASS=findatapass'
    ports:
      - "27018:27017"
    volumes:
      - mongodata:/data/db
      - mongo-configdb:/data/configdb
    networks:
      - invest-system
volumes:
  mongodata:
  mongo-configdb:

networks:
  invest-system:
    external: true
