version: "3.8"
   
services:
  findata:
    container_name: findata_service
    build: .
    depends_on:
      mongodb:
        condition: service_started
      rabbitmq:
        condition: service_started
    networks:
      - invest_system_net
  mongodb:
    image: mongo:4.4-bionic
    container_name: findata_mongodb
    environment:
      - 'MONGODB_USER=findata'
      - 'MONGODB_PASS=findatapass'
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
      - mongo-configdb:/data/configdb
    networks:
      - invest_system_net
  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: invest_system_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "findatauser"
      RABBITMQ_DEFAULT_PASS: "findatauserpass"
      RABBITMQ_DEFAULT_VHOST: "finsystem"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - invest_system_net

volumes:
  mongodata:
  mongo-configdb:

networks:
  invest_system_net:
